### ISSUE TITLE
License and Repository details missing

### ISSUE THREAD

**Issue by manwar** [xsawyerx/test-ping#3]
Hi,

It appears Test::Ping v0.200 distribution has META.yml and META.json generated using Makefile.PL (autogenerated) script. Since the Makefile.PL script was autogenerated by Build.PL script, it is missing LICENSE and REPOSITORY details.

I am not sure how this can be passed to Makefile.PL when it is being auto-generated.

Best Regards,
Mohammad S Anwar

**Comment by xsawyerx** [comment]
Thanks for opening the issue, Mohammad!

I just moved the code to `dzil`. It removes the `Build.PL` and generates the appropriate META data. I released two new versions (one which I screwed up, one which I corrected).

I consider this fixed. Please let me know if you find any other issues. Thanks!
